require("paq")({
    { "savq/paq-nvim" },
    { "nvim-treesitter/nvim-treesitter" },
    { "norcalli/nvim-colorizer.lua" },
    { "marko-cerovac/material.nvim" },
    { "kyazdani42/nvim-web-devicons" },
    { "hoob3rt/lualine.nvim" },
    { "neovim/nvim-lspconfig" },
    { "w0rp/ale" },
    { "tpope/vim-fugitive" },
    { "godlygeek/tabular" },
    { "plasticboy/vim-markdown" },
    { "nvim-lua/popup.nvim" },
    { "nvim-lua/plenary.nvim" },
    { "nvim-telescope/telescope.nvim" },
    { "lambdalisue/fern.vim" },
    { "antoinemadec/FixCursorHold.nvim" },
    { "akinsho/bufferline.nvim" },
    { "windwp/nvim-autopairs" },
    { "myusuf3/numbers.vim" },
    { "fladson/vim-kitty" },
    { "lark-parser/vim-lark-syntax" },
    -- Rust tools
    { "williamboman/mason.nvim" },
    { "williamboman/mason-lspconfig.nvim" },
    { "simrat39/rust-tools.nvim" },
    -- Completion framework:
    { "hrsh7th/nvim-cmp" },
    -- LSP completion source:
    { "hrsh7th/cmp-nvim-lsp" },
    -- Useful completion sources:
    { "hrsh7th/cmp-nvim-lua" },
    { "hrsh7th/cmp-nvim-lsp-signature-help" },
    { "hrsh7th/cmp-vsnip" },
    { "hrsh7th/cmp-path" },
    { "hrsh7th/cmp-buffer" },
    { "hrsh7th/vim-vsnip" },
})
